# -*- coding: utf-8 -*-
"""All the profane words in all forms.

WARNING: The content in this file is, by definition, profane.
"""

profanities = {
    'fi': set([
        u'vittu', u'vitun', u'vittua', u'vitut', u'vitussa', u'vitusta', u'vittuun', u'vitulla', u'vitulta', u'vitulle', u'vitusti',
        u'saatana', u'saatanan', u'saatanaa', u'saatanat', u'saatanassa', u'saatanasta', u'saatanaan', u'saatanalla', u'saatalta', u'saatanalle', u'saatanasti',
        u'perkele', u'perkeleen', u'perkelettä', u'perkeleet', u'perkeleessä', u'perkeleestä', u'perkeleeseen', u'perkeleellä', u'perkeleeltä', u'perkeleelle', u'perkeleesti',
        u'helvetti', u'helvetin', u'helvettiä', u'helvetit', u'helvetissä', u'helvetistä', u'helvettiin', u'helvetillä', u'helvetiltä', u'helvetille', u'helvetisti',
        #u'', u'', u'', u'', u'', u'', u'', u'', u'', u'', u'',
        ]),
    'en': set([
        u'fuck', u'fucks', u'fucking',

        # http://www.bannedwordlist.com/lists/swearWords.txt
        u'anal',
        u'anus',
        u'arse',
        u'ass',
        u'ballsack',
        u'balls',
        u'bastard',
        u'bitch',
        u'biatch',
        u'bloody',
        u'blowjob',
        u'bollock',
        u'bollok',
        u'boner',
        u'boob',
        u'bugger',
        u'bum',
        u'butt',
        u'buttplug',
        u'clitoris',
        u'cock',
        u'coon',
        u'crap',
        u'cunt',
        u'damn',
        u'dick',
        u'dildo',
        u'dyke',
        u'fag',
        u'feck',
        u'fellate',
        u'fellatio',
        u'felching',
        u'fuck',
        u'fudgepacker',
        u'flange',
        U'Goddamn',
        u'God damn',
        u'hell',
        u'homo',
        u'jerk',
        u'jizz',
        u'knobend',
        u'labia',
        u'lmao',
        u'lmfao',
        u'muff',
        u'nigger',
        u'nigga',
        u'omg',
        u'penis',
        u'piss',
        u'poop',
        u'prick',
        u'pube',
        u'pussy',
        u'queer',
        u'scrotum',
        u'sex',
        u'shit',
        u'sh1t',
        u'slut',
        u'smegma',
        u'spunk',
        u'tit',
        u'tosser',
        u'turd',
        u'twat',
        u'vagina',
        u'wank',
        u'whore',
        u'wtf',

        ]),
    }
